services:
  - type: web
    name: pstore
    runtime: docker
    repo: https://github.com/engineershi/pstore
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "8765"
      - key: PSTORE_TAG
        value: ""
      - key: PSTORE_MARKET
        value: com
      - key: PSTORE_ADMIN_PASSWORD
        sync: false