# -*- coding: utf-8 -*-
"""pstore ebook module: turns a trending niche into a stylish, graphic-niched
PDF (pure stdlib, via pdfgen) plus an HTML preview for the admin console.

Generation degrades gracefully: with an AI configured the copy comes from it;
otherwise we use ai.ebook()'s fallback template structure. Always deterministic
enough for tests to sniff the %PDF magic header.
"""
import hashlib
import html
import time

import ai
import pdfgen

ACENTS = [(255, 107, 44), (38, 80, 170), (16, 124, 104), (120, 63, 155)]


def _niche_pick(keyword):
    return (keyword or "trending picks").strip() or "trending picks"


def _hash_seed(niche):
    return int(hashlib.sha1(niche.encode("utf-8")).hexdigest(), 16)


def build_ebook(keyword, hint=""):
    """All-in-one: compute chapters + design then render PDF + HTML.

    Returns dict {keyword, title, subtitle, headline, subheadline, chapters,
    pdf, pdf_name, html_preview, generated_at}. `pdf` is bytes.
    """
    niche = _niche_pick(keyword)
    data = ai.ebook(niche, hint)
    head = ai.headline_and_subheadline(niche, hint)
    title = data["cover"][0] if data["cover"] else head["headline"]
    subtitle = data["cover"][1] if len(data["cover"]) > 1 else head["subheadline"]
    chapters = data["chapters"]
    accent = ACENTS[_hash_seed(niche) % len(ACENTS)]
    pdf = _render_pdf(title, subtitle, chapters, accent)
    return {
        "keyword": keyword,
        "title": title,
        "subtitle": subtitle,
        "headline": head["headline"],
        "subheadline": head["subheadline"],
        "chapters": chapters,
        "pdf": pdf,
        "pdf_name": "%s-ebook.pdf" % (keyword or "picks"),
        "html_preview": _html_preview(title, subtitle, chapters, accent),
        "generated_at": int(time.time()),
    }


def chapter_paragraphs(chapter):
    return [p.strip() for p in chapter.split("\n\n") if p.strip()]


def _render_pdf(title, subtitle, chapters, accent):
    doc = pdfgen.Pdf(accent=accent)
    doc.cover(title, subtitle, kicker="FREE EBOOK")
    for i, ch in enumerate(chapters, 1):
        ctitle = "Chapter %d" % i
        doc.heading(ctitle)
        paras = chapter_paragraphs(ch)
        if not paras:
            paras = [ch]
        for j, para in enumerate(paras):
            if j == 0:
                doc.paragraph(para)
            elif j == len(paras) - 1:
                doc.pullquote(para)
            else:
                doc.paragraph(para)
        if i < len(chapters):
            doc.spacer(14)
            doc.new_page()
    return doc.save()


def _html_preview(title, subtitle, chapters, accent):
    def esc(s):
        return html.escape(s, quote=True)

    rgb = "#%02x%02x%02x" % accent
    cards = []
    for i, ch in enumerate(chapters, 1):
        paras = chapter_paragraphs(ch)
        intro = esc((paras[0] if paras else ch)[:170]) + ("…" if len((paras[0] if paras else ch)) > 170 else "")
        cards.append('<div style="background:#fff;border:1px solid #e8e2da;border-radius:14px;'
                     'padding:18px 20px;flex:1;min-width:220px">'
                     '<div style="color:%s;font-weight:800;letter-spacing:.1em;font-size:12px">'
                     'CHAPTER %d</div>'
                     '<div style="font-weight:700;margin:6px 0 4px;color:#2b2830">%s</div>'
                     '<div style="color:#6b6470;font-size:13px;line-height:1.5">%s</div></div>'
                     % (rgb, i, esc("Chapter %d" % i), intro))
    return ("""<div style="max-width:860px;margin:0 auto">
  <div style="background:%s;border-radius:24px;color:#fff;padding:36px 34px">
    <div style="letter-spacing:.18em;font-size:12px;font-weight:800;opacity:.85">FREE EBOOK</div>
    <div style="font-size:30px;font-weight:800;margin:10px 0 6px">%s</div>
    <div style="opacity:.92;font-size:15px">%s</div>
  </div>
  <div style="background:#fff;border:1px solid #e8e2da;border-radius:16px;margin-top:14px;padding:22px">
    <div style="font-weight:800;color:#2b2830">How it's written</div>
    <div style="color:#6b6470;font-size:14px;line-height:1.6;margin-top:6px">%s</div>
  </div>
  <div style="background:#fff;border:1px solid #e8e2da;border-radius:16px;margin-top:14px;padding:22px">
    <div style="font-weight:800;color:#2b2830">Chapters</div>
    <div style="display:flex;flex-wrap:wrap;gap:12px;margin-top:12px;justify-content:stretch">%s</div>
  </div>
  <div style="font-size:12px;color:#9a939f;margin-top:12px;text-align:center">Generated by pstore engine · your affiliate picks stay direct and tagged</div>
</div>"""
            % (rgb, esc(title), esc(subtitle), esc(subtitle), "".join(cards)))


def latest_pdf_path(keyword):
    """Filesystem cache used by the mail auto-send path."""
    return "/tmp/pstore_ebook_%s.pdf" % (_niche_pick(keyword).replace(" ", "-"))